name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      env:
    #    DOCKER_USER: ${{ secrets.DOCKER_USER}}
         GIT_PASSWORD: ${{ secrets.GIT_PASSWORD}}
      run: |
        docker login docker.pkg.github.com --username ${GITHUB_ACTOR} --password ${GIT_PASSWORD}
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag docker.pkg.github.com/${GITHUB_REPOSITORY}:${GITHUB_REF##*/}

    - name: Pushing to Registry
      run: |
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}:${GITHUB_REF##*/}
