name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Build the Docker image
      env: 
        REPO_NAME: $(echo "${GITHUB_REPOSITORY}" | awk -F / '{print $2}')
      run: |
        docker build . --file Dockerfile --tag docker.pkg.github.com/${GITHUB_REPOSITORY}/REPO_NAME:${GITHUB_REF##*/}

    - name: Pushing to the Registry
      env:
         GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        docker login docker.pkg.github.com --username ${GITHUB_ACTOR} -p ${GIT_TOKEN}  && \
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/REPO_NAME:${GITHUB_REF##*/}




